
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ChakraProv from './components/ChakraProv'

import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const DynamicSelect = dynamic(() => import('@chakra-ui/next-js'), { ssr: false})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* for chakraUI // Hydration error */}

      {/* <ChakraProv> */}

      <body className={inter.className}>{children}</body>
      
      {/* </ChakraProv> */}
      
    </html>
  )
}
